[[bin]]
bench = false
name = "nu_plugin_explore"

[dependencies]
anyhow = "1.0.73"
console = "0.15.7"
crossterm = "0.27.0"
nuon = { git = "https://github.com/nushell/nushell", rev = "59ee96c70d2aa2d1d24d364eebe9c711700e3155", package = "nuon" }
nu-plugin = { git = "https://github.com/nushell/nushell", rev = "59ee96c70d2aa2d1d24d364eebe9c711700e3155", package = "nu-plugin" }
nu-protocol = { git = "https://github.com/nushell/nushell", rev = "59ee96c70d2aa2d1d24d364eebe9c711700e3155", package = "nu-protocol", features = ["plugin"] }
ratatui = "0.26.1"
url = "2.4.0"

[target.'cfg(target_os = "macos")'.dependencies]
crossterm = { version = "0.27.0", features = ["use-dev-tty"] }

[lib]
bench = false

[package]
edition = "2021"
name = "nu_plugin_explore"
version = "0.92.3-2595f31541554c6d8602ebebc9dffbc4dd29dd89"
